### ISSUE TITLE
Can't even build it, immediately get errors

### ISSUE THREAD

**Issue by unoriginalscreenname** [SciPhi-AI/R2R-Dashboard#4]
If you try and build this project on windows 11 you get:  

info - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
Linting and checking validity of types . ELIFECYCLE  Command failed with exit code 1.

Also, hilariously, if you follow the instructions to do a git clone (git clone git@github.com:SciPhi-AI/R2R-Dashboard.git
), you ALSO get a weird message:

The authenticity of host 'github.com (140.82.113.4)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])?

I've never seen that before.  Have you all tried running through your documentation?  I can't seem to get anything to actually work.  why would you not just have git clone SciPhi-AI/R2R-Dashboard.git as the instruction?

**Comment by NolanTrem** [comment]
Hey @unoriginalscreenname thanks for raising this issue after trying to get this running in #1.

I was able to do a clean install of the project on my M1 Macbook Pro running Sonoma 14.4.1 without issue so I believe that this is something with Windows that's causing problems. I'm going to install a virtual machine and will ship a fix to support Windows users, but if you'd like to contribute to the project it would be great to have a Windows user's insight there. I'm not sure if it's a quick fix though, as the differences between Linux/MacOS and Windows binaries are quite stark.

As for the git clone, that looks like an expected behavior. Our preferred install is through ssh, [as it's more secure](https://stackoverflow.com/a/38884654). If you haven't used this before, you will have to select "yes" in the response that you're seeing. If you want, you can alternatively install via HTTP or the Github CLI. If you want to set up the SSH install, [there's some documentation here from Github](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository).

![Screenshot 2024-06-19 at 8 27 37 AM](https://github.com/SciPhi-AI/R2R-Dashboard/assets/34580718/11e90cfb-6dfd-4ce3-9532-0b9ffd7ee72a)
